name: CI (root)

on:
  push:
    branches:
      - "root"

  workflow_dispatch:

permissions:
  contents: write
  id-token: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4

        with:
          java-version: 17
          distribution: temurin

      - name: Set up Kotlin
        uses: fwilhe2/setup-kotlin@main

      - name: Set up Gradle properties

        run: |
          mkdir -p ~/.gradle
          echo "githubToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.gradle/gradle.properties
          echo -e "\norg.gradle.jvmargs=-XX:MaxMetaspaceSize=5G" >> ~/.gradle/gradle.properties

      - name: Gradle (Setup)
        uses: gradle/actions/setup-gradle@v4

        with:
          dependency-graph: generate-and-submit

      - name: Gradle (Build)
        run: "./gradlew checkLicenses build publish"

        env:
          ORG_GRADLE_PROJECT_signingKey: "${{ secrets.GPG_KEY }}"
          ORG_GRADLE_PROJECT_signingPassword: "${{ secrets.GPG_PASSWORD }}"

          KORDEX_MAVEN_USERNAME: "${{ secrets.KORDEX_MAVEN_USERNAME }}"
          KORDEX_MAVEN_PASSWORD: "${{ secrets.KORDEX_MAVEN_PASSWORD }}"

          TOKEN: "${{ secrets.TOKEN }}"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3

        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Containers

        run: |
          docker build -t ghcr.io/kord-extensions/data-collector:latest -t ghcr.io/kord-extensions/data-collector:${GITHUB_SHA} .
          docker push ghcr.io/kord-extensions/data-collector:latest
          docker push ghcr.io/kord-extensions/data-collector:${GITHUB_SHA}
